<?php
/**
 * @file
 *  API for retrieving stock information from Yahoo historical stock data.
 */

/**
 * Implements hook_menu().
 */
function stockinfo_historical_menu() {
  $items = array();
  $items['admin/config/services/stockinfo/historical'] = array(
    'title' => 'Historical Stock Info settings',
    'description' => 'Pull historical data for stocks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stockinfo_historical_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Create the form for Stock Info historical data admin settings.
 */
function stockinfo_historical_admin_settings() {

  $form = array();

  $form['stockinfo_historical_from_date'] = array(
    '#type' => 'date',
    '#title' => t('From Date'),
    '#default_value' => variable_get("stockinfo_historical_from_date", variable_get("stockinfo_historical_from_date_default")),
  );

  $form['stockinfo_historical_symbols'] = array(
    '#type' => 'textarea',
    '#title' => t('Default symbols'),
    '#default_value' => variable_get('stockinfo_historical_symbols', variable_get('stockinfo_default_symbols')),
    '#description' => t('Enter symbols to fetch quotes for, each separated by a space'),
  );

  return system_settings_form($form);
}

/**
 * Processes chunks into individual stocks for processing.
 */
function stockinfo_historical_mapstock($chunk, $symbol = NULL) {
  foreach ($chunk as $stock) {
    stockinfo_historical_process_stock($stock);
  }
}

/**
 * Implements hook_stockinfo_historical_save().
 */
function stockinfo_historical_process_stock($stock) {
  drupal_alter('stockinfo_historical_save', $stock);
  $date = array();
  foreach ($stock as $previous_stock) {

    $sid = db_query("SELECT sid FROM stockinfo_historical WHERE symbol = :symbol AND date = :date", array("symbol" => $symbol, "date" => $previous_stock['date']))->fetchCol();
    if (isset($sid[0])) {
      
    }
    else {
      $entity = entity_create($type, array('type' => $type));
      foreach ($previous_stock as $key => $value) {
        if ($key == "date") {
          $entity->$key = $value;
          $entity->symbol = $symbol;
        }
        else {
          $entity->{$key} = $value;
        }
      }
      entity_save("stockinfo_historical", $entity);
    }
  }
}

function stockinfo_stockinfo_historical_save_alter(&$stock) {
  foreach ($stock as &$row) {
    foreach ($row as $property => &$value)
      if ($property == "date") {
        $value = strtotime($value);
      }
  }
}

/**
 * Processes batch of historical stock data.
 */
function stockinfo_fetch_historical_data($batch) {
  $symbols = explode(" ", variable_get("stockinfo_historical_symbols", variable_get('stockinfo_default_symbols')));
  $stock_array = array();
  foreach ($symbols as $symbol) {
    $stock = stockinfo_historical_fetch($symbol);
    $stock_array[] = $stock;
  }
  $stock_chunks = array_chunk($stock_array, 200);
  foreach ($stock_chunks as $chunk) {
    $batch['operations'][] = array('stockinfo_historical_mapstock', array($chunk, $symbol));
  }
  batch_set($batch);
  batch_process("/admin/config/services/stockinfo/historical");
}

/**
 * Generates batch, passes it to relevant function.
 */
function stockinfo_historical_batch_generate() {

  $batch = array(
    'operations' => array(),
    'title' => t('Processing Historical Stock Import'),
    'finished' => 'stockinfo_import_batch_finished',
    'init_message' => t('Import is starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Import has encountered an error.'),
  );

  stockinfo_fetch_historical_data($batch);
}

/**
 * Implements hook_entity_info().
 */
function stockinfo_historical_entity_info() {

  $info = array();
  $info['stockinfo_historical'] = array(
    'label' => t('Stock Info Historical'),
    'plural label' => t('Stock Info Historical'),
    'base table' => 'stockinfo_historical',
    'entity keys' => array(
      'id' => 'sid',
      'label' => 'symbol',
    ),
    'module' => 'stockinfo',
    'views controller class' => 'EntityDefaultViewsController',
    'controller class' => 'EntityAPIController',
    'access callback' => 'stock_info_access_callback',
    'fieldable' => TRUE,
  );

  return $info;
}

/**
 * Implement hook_rules_action_info().
 */
function stockinfo_historical_rules_action_info() {
  return array(
    'stockinfo_historical_rules_action_pull_historical_stock_data' => array(
      'label' => t('Pull Historical Stock Data'),
      'group' => t('Stockinfo'),
    ),
  );
}

/**
 *  This callback fetches the historical stock data.
 */
function stockinfo_historical_rules_action_pull_historical_stock_data() {
  stockinfo_historical_batch_generate();
}

/**
 * Implementation of hook_cron_queue_info().
 */
function stockinfo_historical_cron_queue_info() {
  $queues['stockinfo'] = array(
    'worker callback' => 'stockinfo_historical_run', // This is the callback function for each queue item.
  );
  return $queues;
}

/**
 * Queues historical stockinfo items.
 */
function stockinfo_historical_queue_it() {
  $symbols = explode(" ", variable_get("stockinfo_symbols", variable_get('stockinfo_default_symbols')));
  $stocks = stockinfo_fetch($symbols);
  if ($stocks == FALSE) {
    watchdog("Stockinfo", "Error, symbols are not an array");
    return;
  }
  $queue = DrupalQueue::get('stockinfo_historical');
  foreach ($stocks as $item) {
    $queue->createItem($item);
  }
}

/**
 * Implementation of hook_cron().
 */
function stockinfo_historical_cron() {
  stockinfo_historical_queue_it();
}

/**
 * Worker Callback for the historical stockinfo cron queue.
 */
function stockinfo_historical_run($item) {
  stockinfo_historical_process_stock($item);
}

/**
 * Saves stockinfo entity.
 */
function stockinfo_historical_save($stockinfo) {
  if ($stockinfo->is_new) {
    $sid = db_insert('stockinfo')
        ->useDefaults(array('sid'))
        ->fields(array(
          'symbol' => $stockinfo->symbol,
          'name' => isset($stockinfo->name) ? $stockinfo->name : NULL,
          'created' => REQUEST_TIME,
          'changed' => REQUEST_TIME,
        ))
        ->execute();

    $stockinfo->sid = $sid;
    $stockinfo->revision = TRUE;
  }
  if (!empty($stockinfo->revision)) {
    $vid = db_insert('stockinfo_revision')
        ->useDefaults(array('vid'))
        ->fields(array(
          'sid' => $stockinfo->sid,
          'symbol' => $stockinfo->symbol,
          'name' => isset($stockinfo->name) ? $stockinfo->name : NULL,
          'changed' => REQUEST_TIME,
        ))
        ->execute();

    $stockinfo->vid = $vid;

    db_update('stockinfo')
        ->condition('sid', $stockinfo->sid)
        ->fields(array(
          'vid' => $stockinfo->vid,
          'symbol' => $stockinfo->symbol,
          'name' => isset($stockinfo->name) ? $stockinfo->name : NULL,
        ))
        ->execute();
  }

  // let Field UI deal with the fields.
  if ($stockinfo->is_new) {
    field_attach_insert('stockinfo', $stockinfo);
  }
  else {
    field_attach_update('stockinfo', $stockinfo);
  }

  return $stockinfo->sid;
}
